import React,{useEffect,useMemo,useState} from 'react';
import {signInWithEmailAndPassword,signOut,onAuthStateChanged,updatePassword} from 'firebase/auth';
import {collection,doc,getDoc,getDocs,query,where} from 'firebase/firestore';
import {auth,db} from './firebase';
import {setSigningPin,signActaWithPin} from './config/signingApi';

const green='#31533a',bright='#3dad2d',bg='#f5f7f2',border='#dfe5dc',muted='#667268';
const input={width:'100%',boxSizing:'border-box',padding:'10px 12px',border:`1px solid ${border}`,borderRadius:9,fontSize:14,background:'#fff'};
const btn=(kind='primary')=>({border:0,borderRadius:9,padding:'10px 14px',fontWeight:800,cursor:'pointer',background:kind==='primary'?bright:kind==='danger'?'#b93333':'#e9eee7',color:kind==='primary'||kind==='danger'?'#fff':green});

function Login(){
 const [username,setUsername]=useState(''),[pass,setPass]=useState(''),[show,setShow]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const authEmail=u=>`${String(u||'').trim().toLowerCase()}@firmas.nodo.app`;
 async function go(){const u=String(username||'').trim().toLowerCase();if(!u||!pass){setMsg('Captura usuario y contraseña.');return}setBusy(true);setMsg('');try{await signInWithEmailAndPassword(auth,authEmail(u),pass)}catch(e){console.error(e);setMsg('No fue posible iniciar sesión. Verifica tu usuario y contraseña.')}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:bg,display:'grid',placeItems:'center',fontFamily:'Arial,sans-serif',padding:20}}><div style={{width:'min(430px,100%)',background:'#fff',border:`1px solid ${border}`,borderRadius:16,padding:24}}><div style={{textAlign:'center'}}><img src="/logo-asociacion-comercio-justo.png" alt="" style={{width:150,maxHeight:120,objectFit:'contain'}}/><h2 style={{color:green,marginBottom:3}}>Portal de Firmas NODO</h2><div style={{fontSize:12,color:muted}}>Asociación de Comercio Justo Campos Bórquez A.C.</div></div><label style={{display:'block',fontSize:12,fontWeight:800,color:green,marginTop:20}}>Usuario</label><input style={{...input,margin:'5px 0 12px'}} autoCapitalize="none" autoCorrect="off" value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/\s+/g,''))}/><label style={{display:'block',fontSize:12,fontWeight:800,color:green}}>Contraseña de acceso</label><div style={{position:'relative',marginTop:5}}><input style={{...input,paddingRight:85}} type={show?'text':'password'} value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/><button type="button" onClick={()=>setShow(v=>!v)} style={{position:'absolute',right:7,top:'50%',transform:'translateY(-50%)',border:0,background:'transparent',color:green,fontWeight:800}}>{show?'Ocultar':'Mostrar'}</button></div><button style={{...btn(),width:'100%',marginTop:14}} disabled={busy} onClick={go}>{busy?'Ingresando…':'Ingresar a mis documentos'}</button>{msg&&<div style={{marginTop:12,padding:10,borderRadius:8,background:'#fff0f0',color:'#912727',fontSize:12}}>{msg}</div>}<p style={{fontSize:10,color:muted,marginTop:18}}>Tu usuario y contraseña permiten entrar a tu cuenta. El PIN de firma es independiente y se solicita únicamente al firmar.</p></div></main>
}

export default function FirmaPortal(){
 const [user,setUser]=useState(undefined),[perfil,setPerfil]=useState(null),[docs,setDocs]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const [pin,setPin]=useState(''),[pin2,setPin2]=useState(''),[currentPin,setCurrentPin]=useState(''),[showPinSetup,setShowPinSetup]=useState(false),[newPass,setNewPass]=useState('');
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u||null);setMsg('');if(u){try{const p=await getDoc(doc(db,'usuariosNodo',String(u.email||'').trim().toLowerCase()));setPerfil(p.exists()?p.data():null)}catch{setPerfil(null)}}else{setPerfil(null);setDocs([]);setSelected(null)}}),[]);
 async function loadDocs(u=user){if(!u?.uid)return;setBusy(true);setMsg('');try{const s=await getDocs(query(collection(db,'actaFirmas'),where('firmanteUid','==',u.uid)));setDocs(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.fecha||b.creadoEn||'').localeCompare(String(a.fecha||a.creadoEn||''))))}catch(e){console.error(e);setMsg(`No se pudieron cargar tus documentos: ${e?.message||'error de acceso'}`)}finally{setBusy(false)}}
 useEffect(()=>{if(user)loadDocs(user)},[user?.uid]);
 const pending=useMemo(()=>docs.filter(x=>x.estado!=='Firmado'),[docs]);
 const signed=useMemo(()=>docs.filter(x=>x.estado==='Firmado'),[docs]);
 async function savePin(){if(!/^\d{6}$/.test(pin)){setMsg('El PIN de firma debe tener exactamente 6 dígitos.');return}if(pin!==pin2){setMsg('Los PIN no coinciden.');return}setBusy(true);try{await setSigningPin({newPin:pin,currentPin});setPin('');setPin2('');setCurrentPin('');setShowPinSetup(false);setMsg('PIN de firma configurado correctamente.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function signDoc(){if(!selected)return;if(!/^\d{6}$/.test(pin)){setMsg('Captura tu PIN de firma de 6 dígitos.');return}if(!confirm(`¿Firmar electrónicamente “${selected.titulo}”? Esta acción queda registrada y no puede deshacerse desde tu portal.`))return;setBusy(true);setMsg('Generando firma…');try{const out=await signActaWithPin({firmaId:selected.id,pin});setPin('');setMsg(`Documento firmado correctamente. Cadena: ${out.signatureCode}`);await loadDocs();const fresh={...selected,estado:'Firmado',firmaNodo:out.firmaNodo};setSelected(fresh)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function changePassword(){if(newPass.length<6){setMsg('La contraseña debe tener al menos 6 caracteres.');return}try{await updatePassword(auth.currentUser,newPass);setNewPass('');setMsg('Contraseña de acceso actualizada.')}catch(e){setMsg(e?.code==='auth/requires-recent-login'?'Cierra sesión y vuelve a entrar antes de cambiar la contraseña.':'No fue posible cambiar la contraseña.')}}
 if(user===undefined)return <div style={{fontFamily:'Arial',padding:30}}>Cargando Portal de Firmas…</div>;
 if(!user)return <Login/>;
 return <div style={{minHeight:'100vh',background:bg,fontFamily:'Arial,sans-serif',color:'#263329'}}><header style={{background:green,color:'#fff',padding:'12px 18px'}}><div style={{maxWidth:1040,margin:'0 auto',display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div style={{display:'flex',alignItems:'center',gap:10}}><img src="/logo-asociacion-comercio-justo.png" alt="" style={{height:48,width:48,objectFit:'contain',background:'#fff',borderRadius:9}}/><div><b>Portal de Firmas NODO</b><div style={{fontSize:11,opacity:.85}}>{perfil?.nombre||perfil?.usuario||'Firmante'}</div></div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button style={btn('secondary')} onClick={()=>setShowPinSetup(v=>!v)}>PIN de firma</button><button style={btn('secondary')} onClick={()=>signOut(auth)}>Cerrar sesión</button></div></div></header><main style={{maxWidth:1040,margin:'0 auto',padding:20}}>
 {perfil?.activo===false&&<div style={{padding:14,background:'#fff0f0',borderRadius:10,color:'#8d2626'}}>Tu cuenta está desactivada. Contacta a Administración.</div>}
 {showPinSetup&&<div style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:16,marginBottom:14}}><h3 style={{color:green,marginTop:0}}>Configurar / cambiar PIN de firma</h3><p style={{fontSize:12,color:muted}}>Usa un PIN de 6 dígitos distinto de tu contraseña. Si ya tenías PIN, captura también el PIN actual.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8}}><input style={input} type="password" inputMode="numeric" maxLength={6} placeholder="PIN actual (si existe)" value={currentPin} onChange={e=>setCurrentPin(e.target.value.replace(/\D/g,''))}/><input style={input} type="password" inputMode="numeric" maxLength={6} placeholder="Nuevo PIN (6 dígitos)" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/><input style={input} type="password" inputMode="numeric" maxLength={6} placeholder="Confirmar nuevo PIN" value={pin2} onChange={e=>setPin2(e.target.value.replace(/\D/g,''))}/></div><button style={{...btn(),marginTop:9}} disabled={busy} onClick={savePin}>Guardar PIN de firma</button><details style={{marginTop:14}}><summary style={{cursor:'pointer',fontSize:12,fontWeight:800,color:green}}>Cambiar contraseña de acceso</summary><div style={{display:'flex',gap:7,marginTop:8,flexWrap:'wrap'}}><input style={{...input,maxWidth:280}} type="password" placeholder="Nueva contraseña" value={newPass} onChange={e=>setNewPass(e.target.value)}/><button style={btn('secondary')} onClick={changePassword}>Cambiar contraseña</button></div></details></div>}
 {msg&&<div style={{padding:11,background:'#fff',border:`1px solid ${border}`,borderRadius:9,marginBottom:12,fontSize:12,fontWeight:700}}>{msg}</div>}
 <div style={{display:'grid',gridTemplateColumns:'minmax(280px,.9fr) minmax(0,1.4fr)',gap:14,alignItems:'start'}}><section style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:14}}><h2 style={{color:green,marginTop:0,fontSize:18}}>Mis documentos</h2><div style={{fontSize:12,color:muted,marginBottom:10}}>{pending.length} pendiente(s) · {signed.length} firmado(s)</div>{busy&&!docs.length?<div>Cargando…</div>:docs.map(x=><button key={x.id} onClick={()=>{setSelected(x);setPin('');setMsg('')}} style={{display:'block',width:'100%',textAlign:'left',border:`1px solid ${selected?.id===x.id?bright:border}`,background:selected?.id===x.id?'#f2f8ef':'#fff',borderRadius:9,padding:10,marginBottom:7,cursor:'pointer'}}><b style={{color:green}}>{x.tipoDocumento||'Acta'} · {x.titulo}</b><div style={{fontSize:11,color:muted,marginTop:3}}>{x.fecha||''} {x.hora||''} · {x.estado||'Pendiente'}</div></button>)}{!docs.length&&!busy&&<div style={{fontSize:12,color:muted}}>No tienes documentos asignados.</div>}</section>
 <section style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:18,minHeight:260}}>{!selected?<div style={{color:muted}}>Selecciona un documento para revisarlo.</div>:<><h2 style={{color:green,marginTop:0}}>{selected.tipoDocumento}: {selected.titulo}</h2><div style={{fontSize:12}}><b>Fecha:</b> {selected.fecha} {selected.hora||''}<br/><b>Participante:</b> {selected.nombre}<br/><b>Versión:</b> {selected.versionDocumento||1}<br/><b>Estado:</b> {selected.estado}</div>{[['Orden del día',selected.ordenDia],['Desarrollo',selected.desarrollo],['Acuerdos, responsables y fechas',selected.acuerdos],['Observaciones',selected.observaciones]].filter(([,v])=>v).map(([k,v])=><div key={k} style={{marginTop:16}}><b style={{color:green,fontSize:12}}>{k}</b><div style={{whiteSpace:'pre-wrap',padding:10,background:'#f8faf6',borderRadius:8,fontSize:12,lineHeight:1.5,marginTop:4}}>{v}</div></div>)}{selected.estado==='Firmado'?<div style={{marginTop:18,padding:13,background:'#edf7ea',borderRadius:9}}><b style={{color:green}}>Firmado electrónicamente en NODO</b><div style={{fontSize:11,marginTop:5}}>Fecha/hora: {selected.firmaNodo?.signedAt?new Date(selected.firmaNodo.signedAt).toLocaleString('es-MX'):'—'}<br/>Hash SHA-256: <span style={{wordBreak:'break-all'}}>{selected.firmaNodo?.documentHash||'—'}</span><br/>Cadena de firma: <b style={{wordBreak:'break-all'}}>{selected.firmaNodo?.signatureCode||'—'}</b></div></div>:<div style={{marginTop:18,padding:13,border:`1px solid ${border}`,borderRadius:9}}><p style={{fontSize:12,marginTop:0}}>Al firmar declaras que revisaste esta versión cerrada y manifiestas tu conformidad con su contenido.</p><input style={{...input,maxWidth:230}} type="password" inputMode="numeric" maxLength={6} placeholder="PIN de firma (6 dígitos)" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/><button style={{...btn(),marginLeft:7}} disabled={busy||perfil?.activo===false} onClick={signDoc}>{busy?'Procesando…':'Firmar documento'}</button><div style={{fontSize:10,color:muted,marginTop:8}}>Si aún no tienes PIN, usa “PIN de firma” en la parte superior para configurarlo.</div></div>}<p style={{fontSize:10,color:muted,marginTop:18}}>La Firma NODO es una firma electrónica institucional con trazabilidad criptográfica. No se presenta como e.firma/FIEL ni como Firma Electrónica Avanzada.</p></>}</section></div></main></div>
}
